[tool.poetry]
name = "mueditor"
version = "0.1.0"
description = ""
authors = ["me"]

[tool.poetry.dependencies]
python = "^3.7"
mu-editor = "^1.0.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
